"""Slack bot that answers messages using the Claude Code CLI as its agent backend.

Design notes:
- No ANTHROPIC_API_KEY is used anywhere. Replies are generated by shelling out to
  `claude -p ...`, which authenticates using whatever subscription login the
  operator already set up via an interactive `claude` / `claude /login` session.
  Do NOT pass --bare here: bare mode forces API-key auth and skips the stored
  OAuth/subscription credentials.
- The agent runs in "chat only" mode: permission-settings.json denies every
  tool (Bash/Read/Write/Edit/Glob/Grep/WebFetch/WebSearch/Agent/Monitor), and
  --permission-mode dontAsk means anything not explicitly allowed is refused
  instead of blocking on a prompt (which would hang, since this process has no
  TTY). The result is a pure text Q&A agent with no filesystem or network
  access, regardless of what a Slack user asks it to do.
- One Claude session per Slack thread: the CLI's --resume/session_id lets a
  thread's follow-up messages continue the same conversation.
"""

import json
import logging
import os
import subprocess
import threading

from apscheduler.schedulers.background import BackgroundScheduler
from dotenv import load_dotenv
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

import bot_supabase

# override=True: .envの値を常に優先する。指定しないと、シェルやOSに同名の
# 環境変数(例: 過去のテストで残ったALERT_HOUR)が既に存在する場合、
# load_dotenv()はそれを上書きせず.envの値が無視されてしまう。
load_dotenv(override=True)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("slack-claude-bot")

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
WORKSPACE_DIR = os.path.join(BASE_DIR, "workspace")
SETTINGS_PATH = os.path.join(BASE_DIR, "permission-settings.json")
SESSIONS_PATH = os.path.join(BASE_DIR, "sessions.json")

CLAUDE_BIN = os.environ.get("CLAUDE_BIN", "claude")
CLAUDE_TIMEOUT_SECONDS = int(os.environ.get("CLAUDE_TIMEOUT_SECONDS", "120"))
WEB_APP_URL = os.environ.get("WEB_APP_URL", "http://localhost:3000")

# 期日アラートは常に日本時間で解釈する。JOB_STORE等はデフォルト(メモリ)のままなので、
# タイムゾーンだけはOS/環境変数のロケールに関わらずここで固定しておく。
ALERT_TIMEZONE = "Asia/Tokyo"


def _parse_alert_time(value: str) -> tuple[int, int]:
    """ALERT_HOURを (hour, minute) にパースする。'H' 形式(例: 9)と
    'H:MM' 形式(例: 15:52)の両方を受け付ける。"""
    value = value.strip()
    hour_str, _, minute_str = value.partition(":")
    try:
        hour = int(hour_str)
        minute = int(minute_str) if minute_str else 0
    except ValueError:
        raise ValueError(f"ALERT_HOURの形式が不正です: {value!r} (例: 9 または 15:52)") from None
    if not (0 <= hour <= 23 and 0 <= minute <= 59):
        raise ValueError(f"ALERT_HOURの値が範囲外です: {value!r} (時は0-23、分は0-59)")
    return hour, minute


_ALERT_HOUR_RAW = os.environ.get("ALERT_HOUR", "9:00")
ALERT_HOUR, ALERT_MINUTE = _parse_alert_time(_ALERT_HOUR_RAW)
logger.info(
    "ALERT_HOUR環境変数を読み込みました: %r -> %d時%d分 (JST)",
    _ALERT_HOUR_RAW,
    ALERT_HOUR,
    ALERT_MINUTE,
)

SYSTEM_PROMPT = (
    "You are answering inside a Slack thread. Keep replies concise. "
    "Format using Slack mrkdwn only (*bold*, _italic_, `code`, ```code blocks```) "
    "-- never GitHub-style markdown headers or tables. "
    "You have no tools available (no file, shell, or web access) in this "
    "conversation: answer from your own knowledge and reasoning only, and say "
    "so plainly if a request genuinely requires a tool you don't have. "
    "The user's message may be followed by a JSON block of project/task/member "
    "data fetched on their behalf from the project management system -- if "
    "present, answer strictly from that data and say plainly when something "
    "isn't covered by it; never invent projects, tasks, or members that "
    "aren't in the data."
)

_sessions_lock = threading.Lock()


def _load_sessions():
    if not os.path.exists(SESSIONS_PATH):
        return {}
    try:
        with open(SESSIONS_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        logger.warning("sessions.json was unreadable; starting fresh")
        return {}


def _save_session(thread_key: str, session_id: str):
    with _sessions_lock:
        sessions = _load_sessions()
        sessions[thread_key] = session_id
        with open(SESSIONS_PATH, "w", encoding="utf-8") as f:
            json.dump(sessions, f)


def _clear_session(thread_key: str):
    with _sessions_lock:
        sessions = _load_sessions()
        if sessions.pop(thread_key, None) is not None:
            with open(SESSIONS_PATH, "w", encoding="utf-8") as f:
                json.dump(sessions, f)


def _get_session(thread_key: str):
    with _sessions_lock:
        return _load_sessions().get(thread_key)


def ask_claude(prompt: str, thread_key: str) -> str:
    """Run `claude -p` for one turn and return the text to post back to Slack."""
    session_id = _get_session(thread_key)

    cmd = [
        CLAUDE_BIN,
        "-p",
        prompt,
        "--permission-mode",
        "dontAsk",
        "--settings",
        SETTINGS_PATH,
        "--append-system-prompt",
        SYSTEM_PROMPT,
        "--output-format",
        "json",
    ]
    if session_id:
        cmd += ["--resume", session_id]

    try:
        proc = subprocess.run(
            cmd,
            cwd=WORKSPACE_DIR,
            capture_output=True,
            text=True,
            encoding="utf-8",
            timeout=CLAUDE_TIMEOUT_SECONDS,
        )
    except FileNotFoundError:
        logger.exception("claude binary not found")
        return (
            "⚠️ `claude` コマンドが見つかりませんでした。Claude Code CLI が"
            "インストールされ、PATH に登録されているか確認してください。"
        )
    except subprocess.TimeoutExpired:
        logger.warning("claude -p timed out after %ss", CLAUDE_TIMEOUT_SECONDS)
        return "⚠️ 応答がタイムアウトしました。もう一度試してください。"

    if proc.returncode != 0:
        logger.error("claude -p exited %s: %s", proc.returncode, proc.stderr[:2000])
        # A stale/expired session id is the most common resumable failure —
        # retry once as a brand-new session before giving up.
        if session_id:
            _clear_session(thread_key)
            return ask_claude(prompt, thread_key)
        return f"⚠️ エラーが発生しました:\n```{proc.stderr.strip()[:1500]}```"

    try:
        payload = json.loads(proc.stdout)
    except json.JSONDecodeError:
        logger.error("could not parse claude output: %s", proc.stdout[:2000])
        return "⚠️ Claude の応答を解析できませんでした。"

    new_session_id = payload.get("session_id")
    if new_session_id:
        _save_session(thread_key, new_session_id)

    return payload.get("result") or "(空の応答でした)"


app = App(token=os.environ["SLACK_BOT_TOKEN"])


def _resolve_profile(user_id: str):
    """Look up the Supabase profile linked to this Slack user.

    Returns (profile_or_None, supabase_configured). supabase_configured is
    False only when SUPABASE_URL/SUPABASE_SERVICE_ROLE_KEY are missing, so
    callers can tell "not linked" apart from "not set up at all"."""
    try:
        return bot_supabase.find_linked_user(user_id), True
    except RuntimeError:
        logger.warning("Supabase is not configured; answering without project data")
        return None, False
    except Exception:
        logger.exception("failed to resolve linked Supabase user for slack user %s", user_id)
        return None, False


def _try_direct_project_answer(profile: dict | None, text: str) -> str | None:
    """If the question names one of the questioner's projects directly, answer
    from bot_supabase's deterministic summary (no Claude call) rather than
    routing through the JSON-context+Claude path. Returns None to fall back
    when there's no profile or no project name match."""
    if profile is None:
        return None
    try:
        return bot_supabase.answer_question_about_project(profile["id"], text)
    except Exception:
        logger.exception("failed to build direct project answer for user %s", profile["id"])
        return None


def _build_prompt(profile: dict | None, text: str) -> str:
    """Enrich the raw question with the questioner's permitted project/task/member
    data so Claude can answer it, without ever giving Claude its own DB access
    (see bot_supabase.py's module docstring for why this shape is safe)."""
    if profile is None:
        return (
            f"{text}\n\n"
            "---\n"
            "(system note to Claude: this Slack account is not yet linked to the "
            "project management system. Tell the user, in Japanese, to run `/link` "
            f"in Slack and enter the code shown at {WEB_APP_URL}/settings/slack to "
            "enable project/task/member questions.)"
        )

    try:
        bundle = bot_supabase.get_context_bundle(profile["id"])
    except Exception:
        logger.exception("failed to fetch context bundle for user %s", profile["id"])
        return text

    return (
        f"{text}\n\n"
        "---\n"
        f"質問者: {profile['display_name']}\n"
        "以下は質問者が参加しているプロジェクトのデータです(JSON):\n"
        f"```{json.dumps(bundle, ensure_ascii=False)}```"
    )


def _handle_prompt(say, client, channel: str, thread_ts: str, user_id: str, text: str):
    text = text.strip()
    if not text:
        return

    thread_key = f"{channel}:{thread_ts}"

    if text.lower() in ("reset", "リセット"):
        _clear_session(thread_key)
        say(text="🔄 このスレッドの会話をリセットしました。", thread_ts=thread_ts)
        return

    placeholder = client.chat_postMessage(
        channel=channel, thread_ts=thread_ts, text="🤔 考え中..."
    )

    profile, configured = _resolve_profile(user_id)

    if configured:
        direct_answer = _try_direct_project_answer(profile, text)
        if direct_answer is not None:
            client.chat_update(channel=channel, ts=placeholder["ts"], text=direct_answer)
            return

    prompt = _build_prompt(profile, text) if configured else text
    reply = ask_claude(prompt, thread_key)

    client.chat_update(channel=channel, ts=placeholder["ts"], text=reply)


@app.event("app_mention")
def handle_app_mention(event, say, client):
    channel = event["channel"]
    thread_ts = event.get("thread_ts", event["ts"])
    # Strip the leading "<@BOTID>" mention token.
    text = " ".join(event.get("text", "").split(">", 1)[1:]).strip()
    _handle_prompt(say, client, channel, thread_ts, event.get("user"), text)


@app.event("message")
def handle_direct_message(event, say, client):
    # Only handle plain DMs; channel mentions are handled by app_mention above.
    if event.get("channel_type") != "im":
        return
    if event.get("bot_id") or event.get("subtype"):
        return

    channel = event["channel"]
    thread_ts = event.get("thread_ts", event["ts"])
    _handle_prompt(say, client, channel, thread_ts, event.get("user"), event.get("text", ""))


@app.command("/link")
def handle_link_command(ack, command, client):
    """Issue a one-time code the user redeems at WEB_APP_URL/settings/slack to
    link their Slack identity to their Supabase account (see bot_supabase.py)."""
    ack()
    slack_user_id = command["user_id"]
    team_id = command.get("team_id", "")

    try:
        code = bot_supabase.create_link_code(slack_user_id, team_id)
    except RuntimeError:
        client.chat_postEphemeral(
            channel=command["channel_id"],
            user=slack_user_id,
            text="⚠️ Supabase連携が設定されていないため、この機能は利用できません。",
        )
        return
    except Exception:
        logger.exception("failed to create link code for slack user %s", slack_user_id)
        client.chat_postEphemeral(
            channel=command["channel_id"],
            user=slack_user_id,
            text="⚠️ コードの発行に失敗しました。もう一度試してください。",
        )
        return

    client.chat_postEphemeral(
        channel=command["channel_id"],
        user=slack_user_id,
        text=(
            f"連携コード: `{code}` ({bot_supabase.LINK_CODE_TTL_MINUTES}分間有効)\n"
            f"{WEB_APP_URL}/settings/slack を開いてログインし、このコードを入力してください。"
        ),
    )


def _post_due_alerts():
    """Daily job: fetch newly-due-for-notification tasks and post them to Slack.

    Runs in-process via APScheduler rather than a Supabase Edge Function/pg_cron
    (see plan's design note 3) -- the bot process must stay running for this to fire.
    """
    logger.info("期日アラートチェックを開始します")

    try:
        alerts = bot_supabase.get_due_alerts()
    except RuntimeError:
        logger.warning("Supabase is not configured; skipping due-date alert batch")
        return
    except Exception:
        logger.exception("failed to fetch due-date alerts")
        return

    if not alerts:
        logger.info("期日アラートチェック完了: 通知対象のタスクはありませんでした")
        return

    logger.info("期日アラート対象タスク %d件を送信します", len(alerts))

    for alert in alerts:
        task = alert["task"]
        text = (
            f"⏰ *{alert['label']}*\n"
            f"「{task['title']}」(プロジェクト: {task['project_name']}, 期日: {task['due_date']})"
        )
        for channel_id in alert["channel_ids"]:
            try:
                app.client.chat_postMessage(channel=channel_id, text=text)
            except Exception:
                logger.exception("failed to post due-date alert to channel %s", channel_id)

        if alert["assignee_slack_id"]:
            try:
                dm = app.client.conversations_open(users=alert["assignee_slack_id"])
                app.client.chat_postMessage(channel=dm["channel"]["id"], text=text)
            except Exception:
                logger.exception("failed to DM due-date alert to %s", alert["assignee_slack_id"])


if __name__ == "__main__":
    os.makedirs(WORKSPACE_DIR, exist_ok=True)

    scheduler = BackgroundScheduler(timezone=ALERT_TIMEZONE)
    scheduler.add_job(
        _post_due_alerts,
        "cron",
        hour=ALERT_HOUR,
        minute=ALERT_MINUTE,
        id="due_date_alerts",
    )
    scheduler.start()

    # next_run_timeはスケジューラをstart()した後でないと計算されないため、
    # ここで改めてジョブを取得してログに出す(起動時に一目で確認できるように)。
    due_alert_job = scheduler.get_job("due_date_alerts")
    if due_alert_job and due_alert_job.next_run_time:
        next_run = due_alert_job.next_run_time
        logger.info(
            "期日アラートの次回実行日時は %d月%d日 %d時%d分 です (タイムゾーン: %s)",
            next_run.month,
            next_run.day,
            next_run.hour,
            next_run.minute,
            ALERT_TIMEZONE,
        )
    else:
        logger.warning("期日アラートの次回実行日時を取得できませんでした")

    handler = SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"])
    logger.info("Starting Slack bot (Claude Code backend, chat-only mode)...")
    handler.start()
